platform :ios, '7.0'
inhibit_all_warnings!

target 'KSYFaceUnityPlayerDemo' do
  pod 'GPUImage'
  pod 'KSYMediaPlayer_iOS'
  pod 'FaceUnitySDK',    :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "!!!! #{target.name}"
  end
end
